### ISSUE TITLE
Missing GCP inputs file in docs

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-examples/cloudify-environment-setup#11]
The docs in this repo refer to a non-existent file:
$ cfy install cloudify-environment-setup-latest/gcp-blueprint.yaml -i cloudify-environment-setup-latest/inputs/gcp.yaml --install-plugins --task-retries=30 --task-retry-interval=5

In this case the inputs file "gcp.yaml" does not exist. The other providers are represented, aws, openstack, etc. I will see if I can create one and add it as a PR.

**Comment by EarthmanT** [comment]
added
